-- =====================================================================
-- Benin Life — CORE seed: locations, core game_config, activities   (owner: P1-DB)
-- All inserts are `on conflict do nothing` so admin edits survive re-runs.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Locations (ARCHITECTURE §5 — do not change ids/coords without updating map art)
-- ---------------------------------------------------------------------
insert into public.locations (id, name, district, scene, x, y, risk, night_risk_mult, cctv, keke_ok, congestion, remote_km, actions, sort, blurb) values
('national_museum','Benin National Museum (King''s Square)','oredo','museum',500,500,.15,1.5,true,false,1.3,0,'{activities}',10,
 'Na here the whole Benin history dey siddon — bronze heads, ivory, the works. Ring Road traffic dey circle am like say e be the centre of the world, because e be.'),
('oba_market','Oba Market','oredo','market',445,465,.35,1.8,false,false,1.4,0,'{shop,market_p2p,jobs,activities}',20,
 'Biggest market for Benin — if you no find am for Oba Market, e no dey exist. Hold your bag tight, the crowd no dey joke.'),
('ring_road_pos','Ring Road PoS Line','oredo','pos',565,465,.40,2.0,true,false,1.5,0,'{pos,jobs}',30,
 'Ten PoS umbrellas, one queue, plenty "network no dey". Cash dey flow here, so eye dey watch too.'),
('oba_palace','Oba''s Palace','oredo','palace',545,560,.05,1.0,true,false,1.2,0,'{activities}',40,
 'The royal palace of the Oba of Benin — respect dey here. Greet well, dress decent, and enjoy the culture.'),
('igun_street','Igun Street (Bronze Casters)','oredo','workshop',590,590,.15,1.5,false,true,1.1,0,'{jobs,shop,activities}',50,
 'Bronze casters don dey this street since before your grandpapa grandpapa. Hammer dey knock, fire dey burn, art dey born.'),
('mama_osas_buka','Mama Osas Buka','oredo','buka',455,545,.20,1.5,false,true,1.2,0,'{activities,jobs}',60,
 'Mama Osas owo soup fit make grown man cry. Siddon, wash hand, and no ask for extra meat if you no get change.'),
('new_benin_market','New Benin Market','new_benin','market',585,335,.35,1.8,false,false,1.4,0,'{shop,market_p2p,jobs,activities}',70,
 'Tomato, phone charger, okrika — New Benin Market get everything. Price na "how much you get?"'),
('new_benin_pos','New Benin PoS Junction','new_benin','pos',630,365,.45,2.0,false,false,1.4,0,'{pos,jobs}',80,
 'Busy junction, busy PoS, busy boys wey dey look your pocket. Withdraw quick, comot quicker.'),
('mercy_clinic','Mercy Clinic','new_benin','hospital',545,380,.10,1.2,true,true,1.1,0,'{hospital}',90,
 'Small clinic, big heart. Nurse go check your BP, give you drip, then tell you say na stress — rest abeg.'),
('mission_rd_flats','Mission Road Mini Flats','new_benin','home_flat',520,410,.15,1.6,false,true,1.1,0,'{housing,activities}',100,
 'Self-contain wey get your own toilet — no more morning queue. You don dey move up for life, my guy.'),
('uselu_market','Uselu Market','uselu','market',385,330,.30,1.8,false,false,1.6,0,'{shop,market_p2p,jobs,activities}',110,
 'Uselu Market noise fit wake dead person. Foodstuff cheap, but the go-slow for Lagos Road no cheap at all.'),
('fresh_cut_salon','Fresh Cut Barbing & Salon','uselu','salon',420,295,.20,1.5,false,true,1.1,0,'{jobs,shop,activities}',120,
 'Gen dey hum, clipper dey sing, gist dey flow. Come comot looking like money even if your account dey cry.'),
('uselu_park','Uselu Motor Park','uselu','motorpark',340,365,.40,2.0,false,false,1.6,0,'{jobs,activities}',130,
 '"Lagos! Lagos! One chance remain!" Agberos dey shout, buses dey load, suya dey smoke. Watch your pocket.'),
('uniben','UNIBEN Ugbowo Campus','ugbowo','campus',255,205,.20,1.6,true,true,1.2,0,'{jobs,activities}',140,
 'Great Uniben! Lectures, handouts, and plenty "aspiring" gist under the trees. Strike or no strike, campus dey lively.'),
('ubth','UBTH (Teaching Hospital)','ugbowo','hospital',305,250,.10,1.2,true,false,1.3,0,'{hospital,jobs}',150,
 'Teaching hospital wey sabi patch you back together. Queue long, but the doctors no dey carry last.'),
('back_gate_joint','UNIBEN Back Gate Joint','ugbowo','buka',215,165,.30,2.0,false,true,1.1,0,'{activities}',160,
 'Where students chop noodles-and-egg on credit and argue football till midnight. Cheap food, expensive gist.'),
('wifi_joint','Ugbowo Wi-Fi Joint','ugbowo','cyber',305,170,.25,1.8,false,true,1.0,0,'{jobs,activities}',170,
 'Fast Wi-Fi, loud gen and boys wey dey type like say dem dey write exam. Do your assignment — only legit work here o.'),
('oluku_park','Oluku Junction Park','oluku','motorpark',130,85,.50,2.2,false,false,1.5,0,'{jobs,activities}',180,
 'Gateway to Lagos-Benin expressway. Trailers, buses and hustlers everywhere — no linger for night.'),
('ramat_park','Ramat Park Junction','ikpoba_hill','motorpark',705,375,.40,2.0,false,false,2.2,0,'{jobs,activities}',190,
 'The kingdom of go-slow. Flyover don almost finish since… e go soon finish. Bring patience and small chops.'),
('oregbeni_market','Oregbeni Market (Ikpoba Hill)','ikpoba_hill','market',745,470,.35,1.8,false,false,1.4,0,'{shop,market_p2p,jobs}',200,
 'Up for Ikpoba Hill, market women go call you "my husband" or "fine sister" till you buy something. Na marketing.'),
('aduwawa_park','Aduwawa Motor Park','aduwawa','motorpark',880,400,.55,2.3,false,false,1.4,0,'{jobs,activities}',210,
 'Last stop before Auchi Road. Buses dey load for the north — the road get hold-up gist, so travel for daytime.'),
('aduwawa_room','Aduwawa Face-Me-I-Face-You','aduwawa','home_face_me',850,505,.40,2.0,false,true,1.0,0,'{housing,activities}',220,
 'Ten rooms, one corridor, one bathroom and everybody business na your business. Cheap rent, plenty drama.'),
('third_east','Third East Circular','third_east','street',680,560,.50,3.0,false,false,1.3,0,'{activities,jobs}',230,
 'Daytime e dey busy with shops and spare parts. Night? Omo, no carry phone for hand — boys dey operate.'),
('ekiosa_market','Ekiosa Market','sakponba','market',620,630,.35,1.8,false,false,1.3,0,'{shop,market_p2p}',240,
 'Fresh fish, dry fish, snail and periwinkle — Ekiosa get the soup ingredients wey your mama dey use.'),
('baba_shrine','Baba Osagie Shrine','sakponba','shrine',680,665,.30,1.8,false,true,1.0,0,'{babalawo}',250,
 'Baba Osagie get herbs for everything — headache, bad luck, small "protection". Pay first, believe after.'),
('upper_sakponba','Upper Sakponba','upper_sakponba','street',735,745,.55,3.0,false,true,1.2,0,'{activities,jobs}',260,
 'Upper Sakponba dey jolly for afternoon. When night fall, run go house — this place no dey smile for dark.'),
('santana_market','Santana Market','sapele_rd','market',470,700,.30,1.8,false,false,1.3,0,'{shop,market_p2p}',270,
 'Off Sapele Road, Santana dey sell everything from yam to Ankara. Bargain hard — first price na joke.'),
('sapele_pos','Sapele Road PoS Stand','sapele_rd','pos',510,650,.50,2.2,false,false,1.4,0,'{pos,jobs}',280,
 'Sapele Road PoS na hot spot — plenty cash, plenty eyes. Withdraw small-small and no form big man.'),
('bronze_lounge','Bronze Lounge','sapele_rd','club',540,765,.35,1.6,true,false,1.2,0,'{activities,jobs}',290,
 'DJ dey drop Afrobeats, Chapman dey cold, and everybody be "boss" for here. Spray money with sense.'),
('police_hq','Police Command HQ (GRA)','gra','police',380,600,.02,1.0,true,false,1.1,0,'{police,jobs}',300,
 'Report case, collect bail, or come visit your guy for cell. Talk respectfully — officer no get your time.'),
('bronze_bank','Bronze Bank (GRA)','gra','bank',415,560,.10,1.3,true,false,1.2,0,'{bank,loans,esusu,jobs}',310,
 'Money wey dey bank no fit enter robber hand. AC cold, queue long, but your money safe.'),
('gra_duplex','GRA Duplex Estate','gra','home_duplex',340,655,.10,1.4,true,false,1.0,0,'{housing,activities}',320,
 'Big gate, quiet street, security man for post. When you reach here, you don arrive for life.'),
('kingdom_lounge','Kingdom Lounge (GRA)','gra','club',325,580,.15,1.4,true,false,1.1,0,'{activities}',330,
 'Classy GRA spot — big boys, soft music, small chops wey cost like one week salary. Dress to impress.'),
('benin_airport','Benin Airport','airport_rd','airport',235,470,.05,1.0,true,false,1.1,0,'{airport}',340,
 'Flights to Lagos and Abuja dey come soon. For now, watch plane land and dream big.'),
('siluko_rd','Siluko Road','siluko','street',330,735,.45,2.2,false,true,1.2,0,'{activities,jobs}',350,
 'Long road full of shops, churches and mechanic. Day na hustle; night, shine your eye well.'),
('ekenwan_room','Ekenwan Face-Me-I-Face-You','ekenwan','home_face_me',205,620,.40,2.0,false,true,1.0,0,'{housing,activities}',360,
 'Your first room for Benin — small, hot, and the landlord dey collect rent on the 1st sharp. Na here hustle start.'),
('iguobazuwa_farm','Iguobazuwa Farm Settlement','iguobazuwa','farm',40,700,.30,2.0,false,false,1.0,22,'{farm,jobs}',370,
 'Far from town, close to the soil. Plant cassava, plantain or pepper — just watch out for harvest thieves.')
on conflict (id) do nothing;

-- ---------------------------------------------------------------------
-- Core game_config (admin-editable; kind 'percent' stored 0–100)
-- ---------------------------------------------------------------------
insert into public.game_config (key, value, category, label, description, kind, min, max) values
-- clock / time
('clock.game_minutes_per_real_minute', '12', 'clock', 'Game minutes per real minute', 'Clock speed. 12 = one game day every 2 real hours.', 'number', 1, 120),
('clock.start_hour_offset', '6', 'clock', 'Clock start offset (hours)', 'Game hours added to the clock (shifts which real time is morning).', 'number', 0, 23),
('clock.night_start_hour', '20', 'clock', 'Night starts (hour)', 'Game hour when night begins (dark map, night risk).', 'number', 0, 23),
('clock.night_end_hour', '6', 'clock', 'Night ends (hour)', 'Game hour when morning returns.', 'number', 0, 23),
('time.real_seconds_per_game_minute', '5', 'time', 'Real seconds per game minute (status timers)', 'How long busy/jail/hospital timers last. Keep = 60 ÷ clock speed to match the clock.', 'number', 0.1, 60),
('time.presence_real_minutes', '3', 'time', 'Presence window (real minutes)', 'Players seen within this many real minutes show in "People here".', 'minutes', 1, 30),
('time.last_seen_throttle_real_seconds', '30', 'time', 'Presence write throttle (real seconds)', 'get_my_state only re-saves last_seen when older than this (keeps realtime quiet). Keep well below the presence window.', 'number', 0, 120),
-- needs
('needs.hunger_per_hour', '4', 'needs', 'Hunger drop / game hour', 'How fast belle dey empty.', 'number', 0, 50),
('needs.energy_per_hour', '3', 'needs', 'Energy drop / game hour', 'How fast player dey tire.', 'number', 0, 50),
('needs.hygiene_per_hour', '2.5', 'needs', 'Hygiene drop / game hour', 'How fast body dey smell.', 'number', 0, 50),
('needs.fun_per_hour', '2', 'needs', 'Fun drop / game hour', 'How fast boredom dey enter.', 'number', 0, 50),
('needs.social_per_hour', '1.5', 'needs', 'Social drop / game hour', 'How fast loneliness dey enter.', 'number', 0, 50),
('needs.stress_per_hour', '1', 'needs', 'Stress rise / game hour', 'Benin life dey add stress small small.', 'number', 0, 50),
('needs.starve_health_per_hour', '2', 'needs', 'Health loss / game hour when starving or exhausted', 'Applied while hunger or energy is 0.', 'number', 0, 50),
('needs.starve_health_floor', '10', 'needs', 'Starvation health floor', 'Starvation decay alone never drops health below this.', 'number', 0, 100),
-- start
('start.cash', '5000', 'start', 'Starting cash', 'Cash a new player lands with.', 'naira', 0, 10000000),
('start.bank', '0', 'start', 'Starting bank balance', 'Bank balance for a new player.', 'naira', 0, 10000000),
('start.need_level', '80', 'start', 'Starting needs level', 'Hunger/energy/hygiene/fun/social at creation.', 'number', 0, 100),
('start.health', '100', 'start', 'Starting health', 'Health at creation.', 'number', 0, 100),
('start.stress', '10', 'start', 'Starting stress', 'Stress at creation.', 'number', 0, 100),
('start.protection_real_minutes', '120', 'start', 'New-player protection (real minutes)', 'No robbery while protected.', 'minutes', 0, 10080),
('start.home_location', '"ekenwan_room"', 'start', 'Starting home location', 'Location id new players live/spawn at.', 'text', null, null),
('start.housing', '"face_me_ekenwan"', 'start', 'Starting housing id', 'Housing id assigned at creation.', 'text', null, null),
-- travel
('travel.city_km_across', '18', 'travel', 'City width (km)', 'Map 1000 units = this many km.', 'number', 1, 100),
('travel.real_seconds_per_game_minute', '1', 'travel', 'Real seconds per game minute of travel', 'Travel runs faster than the clock so trips no too long.', 'number', 0.1, 10),
('travel.min_real_seconds', '3', 'travel', 'Minimum trip (real seconds)', 'Shortest possible trip.', 'number', 0, 120),
('travel.walk.speed_kmh', '5', 'travel', 'Walk speed (km/h)', 'Trekking speed. Ignores traffic.', 'number', 1, 30),
('travel.walk.base_cost', '0', 'travel', 'Walk base cost', 'Flat fare for walking.', 'naira', 0, 100000),
('travel.walk.per_km', '0', 'travel', 'Walk cost per km', '', 'naira', 0, 100000),
('travel.keke.speed_kmh', '18', 'travel', 'Keke speed (km/h)', 'Only between keke_ok places.', 'number', 1, 100),
('travel.keke.base_cost', '150', 'travel', 'Keke base fare', '', 'naira', 0, 100000),
('travel.keke.per_km', '100', 'travel', 'Keke fare per km', '', 'naira', 0, 100000),
('travel.bus.speed_kmh', '15', 'travel', 'ECTS bus speed (km/h)', '', 'number', 1, 100),
('travel.bus.base_cost', '300', 'travel', 'ECTS bus flat fare', '', 'naira', 0, 100000),
('travel.bus.per_km', '0', 'travel', 'ECTS bus fare per km', '', 'naira', 0, 100000),
('travel.drop.speed_kmh', '25', 'travel', 'Drop speed (km/h)', 'Ride-hail.', 'number', 1, 100),
('travel.drop.base_cost', '500', 'travel', 'Drop base fare', '', 'naira', 0, 100000),
('travel.drop.per_km', '250', 'travel', 'Drop fare per km', '', 'naira', 0, 100000),
('travel.car.speed_kmh', '30', 'travel', 'Own car speed (km/h)', 'Needs a vehicle item.', 'number', 1, 150),
('travel.car.base_cost', '0', 'travel', 'Car base cost', '', 'naira', 0, 100000),
('travel.car.per_km', '120', 'travel', 'Car fuel per km', '', 'naira', 0, 100000),
-- traffic
('traffic.rush_mult', '1.8', 'traffic', 'Rush-hour multiplier', 'Trip-time multiplier during rush hours.', 'number', 1, 5),
('traffic.rush_am_start', '7', 'traffic', 'Morning rush starts (hour)', '', 'number', 0, 23),
('traffic.rush_am_end', '10', 'traffic', 'Morning rush ends (hour)', '', 'number', 0, 24),
('traffic.rush_pm_start', '16', 'traffic', 'Evening rush starts (hour)', '', 'number', 0, 23),
('traffic.rush_pm_end', '20', 'traffic', 'Evening rush ends (hour)', '', 'number', 0, 24),
('traffic.ramat_mult', '1.6', 'traffic', 'Ramat Park jam multiplier', 'Applied when either end is in ikpoba_hill/aduwawa and the flyover is closed.', 'number', 1, 5),
('traffic.ramat_flyover_open', 'false', 'traffic', 'Ramat Park flyover open', 'Turn on when the flyover opens — removes the Ramat jam.', 'bool', null, null),
-- crime (NPC street robbery baseline)
('crime.npc_base_pct', '6', 'crime', 'Street robbery base %', 'Base chance before zone/night/traffic/cash/mode factors.', 'percent', 0, 100),
('crime.npc_max_pct', '35', 'crime', 'Street robbery max %', 'Hard cap on street robbery chance per trip.', 'percent', 0, 100),
('crime.night_mult', '1', 'crime', 'Global night multiplier', 'Multiplies each location''s night_risk_mult at night.', 'number', 0, 10),
('crime.traffic_weight', '0.5', 'crime', 'Traffic weight', 'How much traffic jams raise robbery chance.', 'number', 0, 5),
('crime.cash_ref', '20000', 'crime', 'Cash reference', 'Cash factor = min(max, min + cash ÷ this).', 'naira', 1, 10000000),
('crime.cash_factor_min', '0.3', 'crime', 'Cash factor minimum', 'Cash factor when carrying little cash.', 'number', 0, 5),
('crime.cash_factor_max', '1.5', 'crime', 'Cash factor maximum', 'Cap for carrying plenty cash.', 'number', 0, 5),
('crime.mode_mult_walk', '1.4', 'crime', 'Robbery mult: walk', '', 'number', 0, 5),
('crime.mode_mult_keke', '1.0', 'crime', 'Robbery mult: keke', '', 'number', 0, 5),
('crime.mode_mult_bus', '0.8', 'crime', 'Robbery mult: ECTS bus', '', 'number', 0, 5),
('crime.mode_mult_drop', '0.7', 'crime', 'Robbery mult: drop', '', 'number', 0, 5),
('crime.mode_mult_car', '0.6', 'crime', 'Robbery mult: own car', '', 'number', 0, 5),
('crime.loss_min_pct', '20', 'crime', 'Robbery loss min %', 'Min share of carried cash taken.', 'percent', 0, 100),
('crime.loss_max_pct', '60', 'crime', 'Robbery loss max %', 'Max share of carried cash taken.', 'percent', 0, 100),
('crime.injury_pct', '15', 'crime', 'Robbery injury chance %', 'Chance a robbery also injures the victim.', 'percent', 0, 100),
('crime.injury_health_min', '15', 'crime', 'Injury health loss min', '', 'number', 0, 100),
('crime.injury_health_max', '35', 'crime', 'Injury health loss max', '', 'number', 0, 100),
('crime.robbery_stress', '15', 'crime', 'Stress added when robbed', '', 'number', 0, 100),
('crime.jail_location', '"police_hq"', 'crime', 'Jail location', 'Where jailed players are held.', 'text', null, null),
('crime.hospital_location', '"ubth"', 'crime', 'Default hospital', 'Where hospitalised players are taken (unless already at a hospital).', 'text', null, null)
on conflict (key) do nothing;

-- ---------------------------------------------------------------------
-- Activities  (effects apply immediately; player is busy for game_minutes)
-- ---------------------------------------------------------------------
insert into public.activities (id, name, scenes, home_only, cost, game_minutes, effects, night_only, sort) values
('sleep', 'Sleep well well', '{home_face_me,home_flat,home_duplex}', true, 0, 480,
  '{"energy": 85, "stress": -20, "health": 5}', false, 10),
('nap', 'Small nap', '{home_face_me,home_flat,home_duplex}', true, 0, 90,
  '{"energy": 25, "stress": -5}', false, 20),
('bathe', 'Baff (bucket and sponge)', '{home_face_me,home_flat,home_duplex}', true, 0, 20,
  '{"hygiene": 60, "stress": -3}', false, 30),
('cook_home', 'Cook rice and stew', '{home_face_me,home_flat,home_duplex}', true, 600, 45,
  '{"hunger": 45, "fun": 5}', false, 40),
('owo_soup', 'Chop owo soup and starch', '{buka}', false, 1500, 30,
  '{"hunger": 55, "fun": 5, "social": 5}', false, 50),
('banga_starch', 'Banga soup and starch', '{buka}', false, 1800, 30,
  '{"hunger": 60, "fun": 8}', false, 60),
('black_soup', 'Black soup with pounded yam', '{buka}', false, 2000, 35,
  '{"hunger": 65, "health": 5}', false, 70),
('noodles_egg', 'Noodles and egg (student budget)', '{buka,cyber}', false, 500, 15,
  '{"hunger": 25}', false, 75),
('pepper_soup', 'Hot goat-meat pepper soup', '{buka,club}', false, 1200, 25,
  '{"hunger": 25, "stress": -10, "fun": 5}', false, 80),
('suya', 'Roadside suya and onions', '{street,motorpark}', false, 700, 15,
  '{"hunger": 25, "fun": 5}', false, 90),
('gist_joint', 'Gist with the guys', '{buka,street,motorpark,salon}', false, 200, 30,
  '{"social": 25, "fun": 10, "stress": -5}', false, 100),
('watch_football', 'Watch football for viewing centre', '{buka,club,street}', false, 300, 120,
  '{"fun": 30, "social": 20, "stress": -8}', false, 110),
('club_night', 'Turn up for club (night)', '{club}', false, 3000, 120,
  '{"fun": 40, "social": 35, "energy": -15, "hygiene": -10, "stress": -20, "street_cred": 1}', true, 120),
('lounge_chill', 'Chapman and small chops', '{club}', false, 2000, 60,
  '{"fun": 20, "social": 20, "hunger": 10, "stress": -5}', false, 130),
('museum_tour', 'Tour the bronze gallery', '{museum}', false, 500, 60,
  '{"fun": 20, "stress": -10, "social": 5}', false, 140),
('palace_visit', 'Visit the palace grounds (respectfully)', '{palace}', false, 200, 45,
  '{"fun": 15, "stress": -10, "social": 5}', false, 150),
('campus_stroll', 'Waka round campus', '{campus}', false, 0, 45,
  '{"fun": 10, "social": 15, "energy": -5}', false, 160),
('bronze_casting', 'Watch bronze casting', '{workshop}', false, 300, 60,
  '{"fun": 25, "stress": -5}', false, 170),
('market_stroll', 'Market waka and price check', '{market}', false, 0, 45,
  '{"fun": 10, "social": 10, "energy": -5}', false, 180),
('cyber_browse', 'Browse and catch up on gist online', '{cyber}', false, 300, 60,
  '{"fun": 20, "social": 10}', false, 190),
('salon_freshen', 'Fresh barb / make hair', '{salon}', false, 1500, 45,
  '{"hygiene": 25, "fun": 10, "social": 5, "stress": -5}', false, 200),
('plane_spotting', 'Watch plane land', '{airport}', false, 0, 30,
  '{"fun": 10, "stress": -5}', false, 210)
on conflict (id) do nothing;
